### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by peer-pri** [avalon60/ctk_theme_builder#12]
python theme_builder_setup.py -i /home/clive/utilities -p /tmp/ctk_theme_builder-2.0.0.zip
  File "theme_builder_setup.py", line 19
    __title__ = f'{PRODUCT} Setup'
                                 ^
SyntaxError: invalid syntax

**Comment by avalon60** [comment]
Hi. That's a really old version. 
Please download https://github.com/avalon60/ctk_theme_builder/releases/download/v2.4.0/ctk_theme_builder-2.4.0.zip
Re-extract the `theme_builder_setup.py` file.
Then, give that a whirl.

**Comment by hsiq** [comment]
Hi, I had a similar problem to the one above, when switching to 2.4.0 I'm having this problem, I don't know what I'm doing wrong, could you help me?

Logs:

C:\Users\revierwere\Downloads>python theme_builder_setup.py -i C:\Users\revierwere -p ctk_theme_builder-2.4.0.zip
Starting CTk_Theme_Builder deployment.
Application home: C:\Users\revierwere
Checking Python interpreter version...
Python version, 3.11.5, is a supported version.
Creating application home: C:\Users\revierwere\ctk_theme_builder
Creating application assets location: C:\Users\revierwere\ctk_theme_builder\assets
Creating application temp location: C:\Users\revierwere\ctk_theme_builder\tmp
Creating application data location: C:\Users\revierwere\ctk_theme_builder\assets\data
Creating user themes location: C:\Users\revierwere\ctk_theme_builder\user_themes
Checking for repository: C:\Users\revierwere\ctk_theme_builder\assets\data\ctk_theme_builder.db
Greenfield installation - creating a new repository.
DEBUG: DB File: C:\Users\revierwere\ctk_theme_builder\assets\data\ctk_theme_builder.db
Unpacking package: C:\Users\revierwere\Downloads\ctk_theme_builder-2.4.0.zip to: C:\Users\revierwere
Inspecting CTk_Theme_Builder application home directory...
The specified application home directory, C:\Users\revierwere\ctk_theme_builder, appears invalid.
The following components are missing:
C:\Users\revierwere\ctk_theme_builder\assets\etc (directory)
C:\Users\revierwere\ctk_theme_builder\assets\themes (directory)
C:\Users\revierwere\ctk_theme_builder\assets\images (directory)
C:\Users\revierwere\ctk_theme_builder\assets\config (directory)
C:\Users\revierwere\ctk_theme_builder\assets\palettes (directory)
C:\Users\revierwere\ctk_theme_builder\assets\views (directory)
C:\Users\revierwere\ctk_theme_builder\ctk_theme_builder.bat (file)
C:\Users\revierwere\ctk_theme_builder\ctk_theme_builder.sh (file)
C:\Users\revierwere\ctk_theme_builder\ctk_theme_preview.py (file)
C:\Users\revierwere\ctk_theme_builder\build_app.sh (file)
C:\Users\revierwere\ctk_theme_builder\build_app.bat (file)
C:\Users\revierwere\ctk_theme_builder\get-pip.py (file)
C:\Users\revierwere\ctk_theme_builder\requirements.txt (file)
C:\Users\revierwere\ctk_theme_builder\assets\config\repo_updates.json (file)
C:\Users\revierwere\ctk_theme_builder\assets\themes\GreyGhost.json (file)
Install base, C:\Users\revierwere, does not appear to be correct.

**Comment by avalon60** [comment]
Apologies @hsiq , been busy with work. I'll take a look at this tonight.

**Comment by avalon60** [comment]
2.5 is now available. This now includes logging for both the app and the installer. You could install and set the main app log level, in Preferences, to "Debug". Providing the logs will help to see what's going on.

@avalon60

 
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).
Assignees
No one—
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
 for this issue or link a pull request.
Notifications
Customize
You’re receiving notifications because you’re watching this repository.
2 participants
@avalon60
@raccoonhands1
 
 Delete issue

**Comment by avalon60** [comment]
Closing - no response.

**Comment by avalon60** [comment]
Closing - no response.
