### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by raccoonhands1** [avalon60/ctk_theme_builder#13]
It opens, but when I attempt to use the features it consistently gives the error "Timeout: Waited too long for preview listener! Ensure that only one instance of CTk Theme Builder is running..." and at the top the window is titled "Please upgrade customtkinter". CustomTkinter is at its latest version for me. Im assuming the app hasn't been upgraded to fit the latest release? CTk v5.2.0

**Comment by avalon60** [comment]
What download did you use?

**Comment by avalon60** [comment]
2.5 is now available. This now includes logging for both the app and the installer. You could install and set the main app log level, in Preferences,  to "Debug". Providing the logs will help to see what's going on.

**Comment by avalon60** [comment]
Closing - no response.
