### ISSUE TITLE
ERROR: Python interpreter version, 3.12.0, is unsupported.

### ISSUE THREAD

**Issue by GasperStef** [avalon60/ctk_theme_builder#19]
Hello,

I am trying to instal Ctk theme builder but there one Error poped out.

`
C:\Windows\System32\apps>python c:\apps\theme_builder_setup.py -p c:\apps\ctk_theme_builder-2.5.0.zip -i c:\apps
Checking Python interpreter version...
ERROR: Python interpreter version, 3.12.0, is unsupported.
Only Python versions between 3.8 and 3.10 are supported
`
I'm using Windows 10 and I have Python 3.12.0.

Is there any solution for this error?

Thank you in advance

**Comment by avalon60** [comment]
> Hello,
> 
> I am trying to instal Ctk theme builder but there one Error poped out.
> 
> `C:\Windows\System32\apps>python c:\apps\theme_builder_setup.py -p c:\apps\ctk_theme_builder-2.5.0.zip -i c:\apps Checking Python interpreter version... ERROR: Python interpreter version, 3.12.0, is unsupported. Only Python versions between 3.8 and 3.10 are supported` I'm using Windows 10 and I have Python 3.12.0.
> 
> Is there any solution for this error?
> 
> Thank you in advance

Hello @GasperStef. Please download []CTk Theme Builder 5.2.1](https://github.com/avalon60/ctk_theme_builder/releases/download/v2.5.1/ctk_theme_builder-2.5.1.zip)

Remember to re-extract theme_builder_setup.py from the file Iit has changed).

You should now, only get a warning, but the install should proceed.

If you get a file not found error. please ensure that you are providing the full pathname to the file that it complains about.

**Comment by avalon60** [comment]
Closing - no response
