### ISSUE TITLE
Invalid literal for int() with base 10: NO_DATA_FOUND (scale_pct)

### ISSUE THREAD

**Issue by KitOakenPurple** [avalon60/ctk_theme_builder#27]
Error handling for NO_DATA_FOUND doesn't seem to work on fresh Windows installs

Python 3.11.8
Windows 11 Pro 24H2 26058.1400, Lenovo Thinkbook 15 G2 ITL (Tested on 2 PCs, one fresh format)

```
Traceback (most recent call last):
  File "c:\ctk_theme_builder-3.0.1\temp\BUILD\ctk_theme_builder\ctk_theme_builder.py", line 79, in <module>
    controller = ControlPanel()
                 ^^^^^^^^^^^^^^
  File "c:\ctk_theme_builder-3.0.1\temp\BUILD\ctk_theme_builder\lib\control_panel_v.py", line 158, in __init__
    control_panel_scale = mod.scaling_float(scale_pct=self.control_panel_scaling_pct)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ctk_theme_builder-3.0.1\temp\BUILD\ctk_theme_builder\lib\ctk_theme_builder_m.py", line 468, in scaling_float
    scaling_float = int(scale_pct.replace("%", "")) / 100
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'NO_DATA_FOUND'
```

**Comment by avalon60** [comment]
Hi @KitOakenPurple.

Could you please zip up the contents of the ctk_theme_builder\log directory and provide uploads them.

Thanks, Clive

**Comment by KitOakenPurple** [comment]
Hi, thanks for looking into this. The log file doesn't say much, so I've zipped up the full directory (without venv) as well in case any other useful information is in here.

I've added pause to ctk_theme_builder.bat to read the error.

[ctk_theme_builder.zip](https://github.com/avalon60/ctk_theme_builder/files/14636721/ctk_theme_builder.zip)

**Comment by avalon60** [comment]
Hi @KitOakenPurple. I can't see an installation log. I am guessing that you unzipped the ZIP file and tried to run the app somehow. If this is the case it won't work. You need to follow the [Installing & Upgrading CTk Theme Builder](https://github.com/avalon60/ctk_theme_builder/wiki/Installing-&-Upgrading-CTk-Theme-Builder) guidance.

**Comment by KitOakenPurple** [comment]
Apologies, I understand the mix-up. I followed the install process, but launching build_app.bat from theme_builder_setup.py hung without response (waited ~15 minutes), so I tried running theme_builder_setup.py after extracting the ZIP.

Fresh install of Python seemed to fix this. Closing the issue, sorry again for the hassle!

**Comment by avalon60** [comment]
> Apologies, I understand the mix-up. I followed the install process, but launching build_app.bat from theme_builder_setup.py hung without response (waited ~15 minutes), so I tried running theme_builder_setup.py after extracting the ZIP.
> 
> Fresh install of Python seemed to fix this. Closing the issue, sorry again for the hassle!

Not a problem. I'm pleased you got it working - happy theme building!
