### ISSUE TITLE
Reporting a Bug When Selecting a Theme , Another Instance of Control Panel Instead of a Preview Panel

### ISSUE THREAD

**Issue by enghoss77** [avalon60/ctk_theme_builder#28]
Hi Clive .. **_Thanks for your Marvelous Contribution_**  ... I am Using Python 3.12 and Just Installed The CTK Theme Builder V3.0.1 Custom Tkinter 5.2.2 ... After Launching The App Normally and When I try to select a Theme from The Default Sliding Menu , The Required Theme is loaded in the Control Panel , But Instead of Getting a Preview Panel Popping up for the selected Theme , I receive another Control Panel at The Reset Configuration , and When I try to interact with the Original Panel , The App Starts to Hanging ( Not Responding ) , and Afterwards , I receive an Error Message ( **Timeout : Waited too long to preview listener ! Ensure That Only one Instance of CTk theme Builder is Running on Port 5051 , and That No Other Process is Using The Port** ).
when I close the original Control Panel , and try to interact with the second control panel window , I start the Same loop again , another control panel window appears instead of the Preview Panel.

_**I Truly Appreciate Your Prompt Feedback on this Bug , and maybe you May Release a new version to avoid this issue**_

![CTk Theme Builder Error 01](https://github.com/avalon60/ctk_theme_builder/assets/44149585/452fffe9-1b70-40e5-af83-427e45ca2154)

Regards,

enghoss77

**Comment by avalon60** [comment]
Hi @enghoss77. Sorry for the inconvenience here. I am struggling to reproduce this on Windows or Linux. I could do with some extra information:

1. What O/S (and version) are you using?
2. How exaclty did you install (please provide all steps from download of the zip).
3. There should be logs in the log ctk_theme_builder/log directory. Please provide these.

NOTE: You don't need to install CustomTkinter, the theme_builder_setup.py / build_app do that for you.

Thanks, Clive

**Comment by enghoss77** [comment]
@avalon60 Thanks for Reaching out Clive ... Here is the Details you asked for ..
1 - I am Using a Windows 11 Pro - Version 22H2 ( OS Build 22621.1413 ) - 64-bit .. 
     My Laptop is Lenovo Yoga 15 - Intel(R) Core i5 - 5200U @220GHz - 16 GB RAM
2 - I Followed The Exact Instructions as per [https://github.com/avalon60/ctk_theme_builder/wiki/Installing-&-Upgrading-CTk-Theme-Builder](url) .. For Windows Deployment , Started By Downloading The Latest ZIP Package Release ( CTk Theme Builder Release 3.0.1 ) .. Unpacked it , Created The Temp Folder and App Folder , Executed The setup Command ( py c:\temp\theme_builder_setup.py -p c:\temp\ctk_theme_builder-3.0.1.zip -i c:\apps ) from the PowerShell at the temp directory that contains the ( theme_builder_setup.py ) and The ZIP Package 3.0.1.
3 - The Log Files are Attached For Your Reference 

The Installation Process went smooth without errors except for a notification about me using Python 3.12.2 and That The Package is completely compatible with 3.11 release of Python , But That Didn't Interrupt The Installation Process.

I am Not Sure if this is the reason for that bug or should I try to downgrade my Python installed Package to 3.11.
I'll just wait for your instructions about that , Hopefully you would figure out this issue .

Keep Me Posted , 

Regards,

[ctk_tb.log](https://github.com/avalon60/ctk_theme_builder/files/14628836/ctk_tb.log)
[theme_builder_setup_2024-03-16_00-18-41.log](https://github.com/avalon60/ctk_theme_builder/files/14628837/theme_builder_setup_2024-03-16_00-18-41.log)
enghoss77

**Comment by avalon60** [comment]
@enghoss77  Assuming that this is resolved, since this has gone quiet. 
 Closed.
