### ISSUE TITLE
Problems running the ctk_theme_builder.bat

### ISSUE THREAD

**Issue by RiemRolle** [avalon60/ctk_theme_builder#29]
After installing customtkinter I downloaded ctk_theme_builder 3.0.1 zip

As documented, i placed this file in a directory, extracted the theme-builder setup.zip and placed this in the same directory
After that via the command prompt i installed the program.   After that i tried to activate the bat file via the command prompt, but with every try i'm asked to install another module, e.g  matplotlib, pyperclip and so on.  The question is, is that normal and what other modules have to be installed before the bat file get excecuted.   I have windows 11, and run Python 3.12

**Comment by avalon60** [comment]
Hi @RiemRolle. The process you described sounds wrong. There is no setup.zip involved in the install process.
The single file which needs to be extracted from the ZIP file is theme_builder_setup.py. Once extracted, you need to run it as described in the [install guide](https://github.com/avalon60/ctk_theme_builder/wiki).

There is also a Windows example described [here](https://github.com/avalon60/ctk_theme_builder/issues/23#issuecomment-1949367942).

Please let me know how you get on.
