### ISSUE TITLE
I can not launch the script for use the apps

### ISSUE THREAD

**Issue by joe00271** [avalon60/ctk_theme_builder#33]
That's the screeshots i am on windows and i tkink i have correctly follow the instruction for install
![Capture d’écran 2024-04-10 000822](https://github.com/avalon60/ctk_theme_builder/assets/149353577/32bec297-71d3-43d2-844e-a978817e654e)
![Capture d’écran 2024-04-10 000954](https://github.com/avalon60/ctk_theme_builder/assets/149353577/76744218-62dd-413c-bec6-215371dce7a6)

**Comment by avalon60** [comment]
It's hard to be sure, but it looks like you are trying to execute the python file directly. Please execute  via the  supplied entry  point script, which for Windows, is ctk_theme_builder.bat. 

This is covered in the installation docs.

**Comment by joe00271** [comment]
@avalon60 the bat file open vscode with the script that's doesn't execute the application

**Comment by avalon60** [comment]
You have a Windows file association with VScode - you'll need to either remove the file association with .py extensions, or edit the last line of the .bat file, to include python at the at the beginnning:

python %PROG_PATH%\controller\ctk_theme_builder.py %1 %2 %3 %4 %5 %6

I need to change that. You are the second person to associate .py files with VScode. The previous guy uninstalled and reinstalled VSvcode to achieve this, although there are other ways to remove the association.

**Comment by joe00271** [comment]
It's good, it's loose when editing the code, it worked

**Comment by avalon60** [comment]
Pleased it worked - happy theme building!
Closing this issue.
