### ISSUE TITLE
Clear everything in preview 

### ISSUE THREAD

**Issue by KorryKatti** [avalon60/ctk_theme_builder#36]
How do I clear everything present in the preview and then start placing the elements I want to and where I want to. Like empty the window which pops up on starting the app

**Comment by avalon60** [comment]
Hi @KorryKatti. For future reference, please raise questions under the Discussions tab, and defects/ehancement requests under Issues. Issues get closed and are more difficult for others to learn from.

If I understand you correctly, you want to empty the Preview Panel of widgets, and add specific widgets which you wish to work on? If so, that is not how CTk Theme Builder is meant to work. The Preview Panel presents all possible CustomTkinter widgets. This allows you to see how your theme updates effect changes. You can also use the QA app to review how your theme looks.

**Comment by KorryKatti** [comment]
Alright will keep that in mind , will look into it
