### ISSUE TITLE
I got a customtkinter module not found with the 3.1.0 version when i'm starting it

### ISSUE THREAD

**Issue by joe00271** [avalon60/ctk_theme_builder#37]
On the menu i have no possibilty to export as a JSON file
![IMG_20240504_082035](https://github.com/avalon60/ctk_theme_builder/assets/149353577/b30b51fc-9dca-4bb6-83ec-aa32a92db905)
![IMG_20240504_082056](https://github.com/avalon60/ctk_theme_builder/assets/149353577/cdb35512-37d0-46d2-be0f-5fc87ef833b3)

**Comment by avalon60** [comment]
Hi @joe00271, the Export / Import options have only just (within the last few minutes) been released, with 3.1.0. Please see the announcements tab.

**Comment by joe00271** [comment]
@avalon60  when i'm starting the app i got a modulenotfoundError

![ctk_theme_builder_error](https://github.com/avalon60/ctk_theme_builder/assets/149353577/a31cb4c8-2883-45eb-9053-90da8a1c15bb)

**Comment by avalon60** [comment]
Hi @joe00271 . Apologies, it sounds like a gashed requirements.txt file - I was having problems with Pyenv and Pycharm not ,working together properly, and thought I had has sorted it.

Please bare with me; my PC is being rebuilt (new case and motherboard). As soon as it's back together, I'll take a look.

**Comment by joe00271** [comment]
@avalon60  ok i will wait

**Comment by avalon60** [comment]
> @avalon60  ok i will wait. do he have any possibility to export a theme that we have create?
> 
> 

You can use Windows Explorer to navigate to the user themes location, and copy them. Just be careful to copy (not cut). You can see the location of where your themes are located, by navigating the menu option Tools > Preferences.

**Comment by avalon60** [comment]
Hi @joe00271. I just retried the 3.1 install on Windows and it worked fine. Can you please relay the steps you went through to install CTk Theme Builder. Thanks.

**Comment by joe00271** [comment]
@avalon60  that's finally work thanks
