### ISSUE TITLE
Install from GitHub "code" button fails

### ISSUE THREAD

**Issue by resnbl** [avalon60/ctk_theme_builder#39]
I ran into the same install problem as #35. The issue appears to be when you download from the GitHub "Code" button (Download  Zip), the default filename is "ctk_theme_builder-develop.zip" and it is packaged under folder name "ctk_theme_builder-develop", probably because the default branch is "develop".

Instead, if I download from the releases page the filename is "ctk_theme_builder-3.0.1.zip" but the internal folder name is "ctk_theme_builder", which installs successfully.

I recommend a (large) note in the "README.md" to select a .zip from the "Releases" section in the right column instead of using the "Code" button.

(PS: I don't know who "Bozzy bear woz", but I chuckled at the "Lorem ipsum", and loved the quote from the best sci-fi movie of all time!)

**Comment by avalon60** [comment]
Hi @resnbl. I have updated the README.md .

Please let me know if it is an improvement and I'll close the ticket.

PS: I am Bozzy Bear - my wife nicknamed me :o)

**Comment by resnbl** [comment]
Yes, I think that is clearer. I'm afraid those of us who frequently download non-PyPi packages are too used to "download first, read the manual later"...

(Glad you cleared up the "Bozzy" bit - I was doubting my sanity and thinking it was a reference to the children's rhyme  "Fuzzy Wuzzy was a bear"...)
