### ISSUE TITLE
Can't see all of left panel

### ISSUE THREAD

**Issue by spinnyarcticfox** [avalon60/ctk_theme_builder#41]
I'm on a 2020 M1 MacBook Air and the bottom of the left panel is cut off. I also can't scroll down on that panel though idk if I'm supposed to be able to.
<img width="1440" alt="Screenshot 2024-05-30 at 2 04 49 PM" src="https://github.com/avalon60/ctk_theme_builder/assets/167834418/aac7454f-817c-40a6-a34a-0c45e28bb87c">

**Comment by spinnyarcticfox** [comment]
Just checked and the full panel does show in full screen.

**Comment by spinnyarcticfox** [comment]
I fixed it by changing the scale. Feeling a little silly.

**Comment by avalon60** [comment]
Good to see someone has it up and running on a Mac 👍
