### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by erentaskiran** [avalon60/ctk_theme_builder#45]
Bu toolu kim yazdıysa onun 7 sülalesini sikeyim. Kim bu docsu yazdıysa onun da aynı şekilde. kardeşim şuna doğru düzgün bi docs yazsanıza kurucam diye ebem sikildi. yapıcağınız programı sikeyim. çalışmıcaksa niye yapıyonuz.

**Comment by avalon60** [comment]
Why did you bother posting an issue? You would have a much better chance of getting it to work, if you were polite and constructive.
