### ISSUE TITLE
The system could not find the path specified

### ISSUE THREAD

**Issue by LucasRibeiroRJBR** [avalon60/ctk_theme_builder#6]
Hello. I followed all the steps but I'm getting this error:

```
O sistema não pode encontrar o caminho especificado.
```

Which translating from portuguese is:

```
The system could not find the path specified.
```

According to the documentation, this system doesn't works on Python 3.11+, so I prompted on my last Python version (3.10.11). The steps I executed is below:

![image](https://github.com/avalon60/ctk_theme_builder/assets/53449579/b2d91d0e-aba3-41dd-ae5b-fc6c0849ae20)

**Comment by avalon60** [comment]
Hi Lucas. That's quite an old version. Can you please try:

https://github.com/avalon60/ctk_theme_builder/releases/download/v2.3.0/ctk_theme_builder-2.3.0.zip

**Comment by LucasRibeiroRJBR** [comment]
Worked to me, thank you!

**Comment by avalon60** [comment]
You are most welcome!
