### ISSUE TITLE
V2.3.0: Tooltips on Windows

### ISSUE THREAD

**Issue by avalon60** [avalon60/ctk_theme_builder#8]
I have noticed that the tool-tip widget is not behaving as expected on Windows. I have raised an issue with the author and hope to provide a fix fairly soon.

**Comment by Akascape** [comment]
@avalon60 I hope it gets fixed by now, I have also added dynamic offset and changed the default alpha value.

**Comment by avalon60** [comment]
Fixed and closed. This fix will be incorporated in 2.4.0
